var BeastConstants = {
  BEASTS_RECEIVED: "BEASTS_RECEIVED",
  BEAST_RECEIVED: "BEAST_RECEIVED",
  ERROR: "BEAST_RECEIVE_ERROR",
  CREATED_BEAST_RECEIVED: "CREATED_BEAST_RECEIVED"
};

module.exports = BeastConstants;
