var BookmarkConstants = {
  BOOKMARKS_RECEIVED: "BOOKMARKS_RECEIVED",
  BOOKMARK_RECEIVED: "BOOKMARK_RECEIVED",
  ERROR: "BOOKMARK_RECEIVE_ERROR",
  REMOVE_BOOKMARK: "REMOVE_BOOKMARK",
  ADD_BOOKMARK: "ADD_BOOKMARK"
};

module.exports = BookmarkConstants;
