var ReviewConstants = {
  REVIEWS_RECEIVED: "REVIEWS_RECEIVED",
  REVIEW_RECEIVED: "REVIEW_RECEIVED",
  ERROR: "REVIEW_RECEIVE_ERROR",
  RESET_ERRORS: "RESET_REVIEW_ERRORS",
  CREATED_REVIEW_RECEIVED: "CREATED_REVIEW_RECEIVED"
};

module.exports = ReviewConstants;
